# Generated by Django 4.1 on 2022-08-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_control', '0002_alter_event_id_alter_performance_actual_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='time_offset',
            field=models.IntegerField(default=0),
        ),
    ]
