# Generated by Django 4.1 on 2022-08-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_control', '0002_alter_event_id_alter_performance_id_alter_venue_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='actual_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
